mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('reserves.urls')),
    url(r'^index$', include('reserves.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reserves/', include('reserves.urls')),
)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reserves/urls.py
from django.conf.urls import patterns, url
from reserves import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^ingresar/$', views.ingresar, name='ingresar'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^nueva_reserva/$', views.nueva_reserva, name='nueva_reserva'),
    url(r'^(?P<reserva_id>\d+)/$', views.detail, name='detail'),
    url(r'^retornar/(?P<objecte_id>\d+)/$', views.retornar, name='retornar'),
    url(r'^eliminar/(?P<reserva_id>\d+)/$', views.eliminar, name='eliminar'),
    url(r'^espai_usuari/$', views.espai_usuari, name='espai_usuari'),
    url(r'^(?P<reserva_id>\d+)/actReserva/$', views.actReserva, name='actReserva'),
)

reserves/models.py
from django.db import models
import datetime
from django.forms import ModelForm
from django.contrib.auth.models import User

class Tipus(models.Model):
    nom = models.CharField(max_length=200)

    def __str__(self):
        return self.nom


class Objecte(models.Model):
    nom = models.CharField(max_length=200)
    tipus = models.ForeignKey(Tipus)
    Si = 'Si'
    No = 'No'
    OPCIONS_DISPONIBLE = (
        (Si, 'Disponible'),
        (No, 'No Disponible'),
    )
    disponible = models.CharField(max_length=50, choices=OPCIONS_DISPONIBLE, default=Si)

    def __str__(self):
        return self.nom


class Salas(models.Model):
    nom = models.CharField(max_length=200)

    def __str__(self):
        return self.nom


class Reserva(models.Model):
    objecte = models.ForeignKey(Objecte)
    user = models.ForeignKey(User, unique=False)
    sala = models.ForeignKey(Salas)
    data_inici = models.DateTimeField('Data inici')
    data_final = models.DateTimeField('Data final')
    data_sol = models.DateTimeField('Data solicitud', default=datetime.datetime.now())

    def demanat_avui(self):
        return self.data_sol.date() == datetime.date.today()

reserves/forms.py
__author__ = 'joaquin'
from django import forms
from models import Reserva
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.admin.widgets import AdminSplitDateTime
class ReservaForm(forms.ModelForm):

    class Meta:
        model = Reserva
        fields = ['objecte', 'user', 'sala', 'data_inici', 'data_final']
        exclude = ['data_sol']

    def __init__(self, *args, **kwargs):
        super(ReservaForm, self).__init__(*args, **kwargs)

        self.fields['data_inici'].widget = AdminDateWidget()
        self.fields['data_final'].widget = AdminDateWidget()

mysite/views.py
from django.http import HttpResponse
from django.conf import settings


def index(request):
    return HttpResponse("Hello, world. You're at HOME index.")
if settings.DEBUG and settings.STATIC_ROOT:
    urlpatterns += patterns('',
        (r'%s(?P<path>.*)$' % settings.STATIC_URL.lstrip('/'),
            'django.views.static.serve',
            {'document_root' : settings.STATIC_ROOT }),)

reserves/views.py
from django.http import Http404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from forms import ReservaForm
from django.contrib.auth import authenticate
from django.contrib.auth import login
import datetime
import pytz
from django.contrib.auth import logout
from models import Reserva, Objecte
utc = pytz.UTC



def index(request):
    list_ult_reserves = Reserva.objects.all().filter(data_final__gt = datetime.date.today()).order_by('data_inici')
    list_old = Reserva.objects.all().filter(data_final__lte = datetime.date.today()).order_by('data_final')[:5]

    context = {'list_ult_reserves': list_ult_reserves, 'list_old': list_old}
    return render(request, 'reserves/index.html', context)

def detail(request,  reserva_id):
    try:
        reserva = Reserva.objects.get(pk=reserva_id)
    except Reserva.DoesNotExist:
        raise Http404
    return render(request, 'reserves/detail.html', {'reserva': reserva})
def actReserva(request):
    pass

@login_required
def espai_usuari(request):

    llista_pendent =  Reserva.objects.all().filter(user__id__icontains=request.user.id).filter(objecte__disponible__icontains='No')
    llista_tornades = Reserva.objects.filter(user__id__icontains=request.user.id).filter(objecte__disponible__icontains='Si')
    return render(request, 'reserves/espai_usuari.html', {'llista_pendent': llista_pendent, 'llista_tornades': llista_tornades,'nomuser': request.user.username})

def logout_view(request):
    auth.logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect("/reserves")

def ingresar(request):
    if request.method == 'POST':
        formulario = AuthenticationForm(request.POST)
        if formulario.is_valid:
            usuario = request.POST['username']
            clave = request.POST['password']
            acceso = authenticate(username=usuario, password=clave)
            if acceso is not None:
                if acceso.is_active:
                    login(request, acceso)
                    return espai_usuari(request)
                else:
                    return render(request, 'reserves/no_actiu.html')
            else:
                return render(request, 'reserves/no_usuari.html')
    else:
        formulario = AuthenticationForm
        return render(request, 'reserves/ingresar.html', {'formulario': formulario})

def signup(request):
    if(request.method == 'POST'):
        formulario= UserCreationForm(request.POST)
        if formulario.is_valid:
            formulario.save()
            return HttpResponseRedirect('/')
    else:
        formulario = UserCreationForm()
    return render(request, 'reserves/signup.html', {'formulario': formulario})
@login_required
def nueva_reserva(request):
    error = 0
    usuario = request.user
    if request.method == 'POST':
        formulario = ReservaForm(request.POST)
        datetime.datetime.utcnow().replace(tzinfo=utc)
        if formulario.is_valid():
            id = request.POST['objecte']
            # selecionamos la fechas para hacer la comparativa

            data_ini = request.POST['data_inici']
            data_final = request.POST['data_final']
            reserva = Reserva.objects.all()

            for element in reserva:
                if(element.objecte==Objecte.objects.get(pk=id)):
                    if(datetime.datetime.strptime(data_ini,"%d/%m/%Y %H:%M").replace(tzinfo=utc) >= element.data_inici and datetime.datetime.strptime(data_ini,"%d/%m/%Y %H:%M").replace(tzinfo=utc) <= element.data_final):
                        error = 1
                        break
                    elif(datetime.datetime.strptime(data_final,'%d/%m/%Y %H:%M').replace(tzinfo=utc) >= element.data_inici and datetime.datetime.strptime(data_final,"%d/%m/%Y %H:%M").replace(tzinfo=utc) <= element.data_final):
                        error = 1
                        break

            if(error!=1):
                obj=Objecte.objects.get(pk=id)
                obj.disponible = 'No'
                obj.save()
                formulario.save()
                return espai_usuari(request)
            else:
                pass
        else:
            messages.error(request, "Error")
    else:
        formulario = ReservaForm()
        #formulario.fields['objecte'].queryset = Objecte.objects.filter(disponible='Si')
        messages.error(request, "Error")

    return render(request, 'reserves/nueva_reserva.html', {'formulario': formulario, 'error':error})

def retornar(request, objecte_id):

    obj = Objecte.objects.get(pk=objecte_id)
    obj.disponible = 'Si'
    obj.save()
    accio = "Reserva Retornada Correctament"
    return espai_usuari(request)

def eliminar(request, reserva_id):

    res = Reserva.objects.get(pk=reserva_id)
    res.delete()
    accio = "Reserva Eliminada Correctament"
    return espai_usuari(request)

def events(request, accio):
    pass

templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Reserves de material {% endblock %}</title>
<script src=" {{ STATIC_URL }}jquery-2.1.1.js"></script>
<link href="{{ STATIC_URL}}style.css" rel="stylesheet" type="text/css">
<script src="{{ STATIC_URL}}efects.js"></script>
</head>
<body>
<div id="titol">
    <h1 class="titol">{% block titol %} Benvingut a Reserves de Material{% endblock %}</h1>
</div>
{% include "nav.html" %}
{% block login %}
<div id="login">
    <span class="login">

       <ul>
           {% if not user.is_authenticated %}
           <a href="{% url 'signup' %}">Registret</a>
           <a href="{% url 'ingresar' %}">Entra</a>
           {% elif user.is_authenticated %}
           Benvingut {{ user.username }}
           <a href="{% url 'logout' %}">Tenca la sessió</a>
           {% endif %}

       </ul>
    </span>
</div>
<br>
{% endblock %}
{% block contingut %}{% endblock %}
{% block peu %}<footer>Programador i desenvolupador : Joaquim Montoliu Aguilera en data 20/11/2014</footer>{% endblock %}

</body>
</html>

templates/nav.html
<nav>
        <ul>
            <li><a href="{% url 'index' %} "><div id="item-menu">Inici</div></a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'nueva_reserva' %}"><div id="item-menu">Nova Reserva</div></a></li>
            <li><a href="{% url 'espai_usuari' %}"><div id="item-menu">Reserves de {{user.username}}</div></a></li>
            {% endif %}

        </ul>
</nav>

templates/reserves/actReserva.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

templates/reserves/detail.html
{% extends 'base.html' %}
<h1>{{ reserva.objecte }}</h1>
{% block contingut %}
<ul class="taula">
    <li>Usuari: {{ reserva.user }}</li>
    <li>Ubicació: {{ reserva.sala }}</li>
    <li>Data d'inici: {{ reserva.data_inici }}</li>
    <li>Data final:{{ reserva.data_final }}</li>
    <li>Data de la solicitud: {{ reserva.data_sol }}</li>
</ul>
{% endblock %}

templates/reserves/espai_usuari.html
{% extends 'base.html' %}

        {% block titol %}<h1 class="titol">Reserves de {{ nomuser }}</h1>{% endblock %}
{% block contingut %}


    {% if llista_pendent %}
        <h2>Les teves Reserves:</h2>
        <ul class="taula">
        {% for reserva in llista_pendent %}
            <li><a href="/reserves/{{ reserva.id }}/">{{ reserva.objecte }}</a> del {{reserva.data_inici}} fins {{reserva.data_final}} <a href="/reserves/retornar/{{ reserva.objecte.id }}/"><span class="retorn">Retornar</span></a></li>
        {% endfor %}
        </ul>
        {% else %}
            <p>No hi han reserves actualment.</p>
    {% endif %}
    <p>Històric de reserves:</p>
        <ul class="taula">
    {% for reserva in llista_tornades %}
            <li>{{ reserva.objecte }} del {{reserva.data_inici}} fins {{reserva.data_final}} <a href="/reserves/eliminar/{{ reserva.id }}/"><span class="eliminar">Eliminar</span></a></li>
        {% endfor %}
        </ul>


{% endblock %}

templates/reserves/index.html
{% extends 'base.html' %}
{% block contingut %}
{% if list_ult_reserves %}
    <span class="tipologies">Reserves Actuals:</span>
    <ul class="taula">
    {% for reserva in list_ult_reserves %}
        <li><a href="/reserves/{{ reserva.id }}/">{{ reserva.objecte }}</a> del {{reserva.data_inici}} fins {{reserva.data_final}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hi han reserves actualment.</p>
{% endif %}

{% if list_old %}
    <span class="tipologies">Reserves pasades:</span>
    <ul class="taula">
    {% for reserva in list_old %}
        <li><a href="/reserves/{{ reserva.id }}/">{{ reserva.objecte }}</a> del {{reserva.data_inici}} fins {{reserva.data_final}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hi ha res al historic.</p>
{% endif %}
{% endblock %}

templates/reserves/ingresar.html
{% extends 'base.html' %}
{% block contingut %}
    <form id='formulario' method="POST"  action="">{% csrf_token %}
        <table>{{ formulario }}</table>
        <input type="submit" value="Entrar">
    </form>
{% endblock %}

templates/reserves/no_actiu.html
{% extends 'base.html' %}
{% block contingut %}
    <h1> El usuari Existeix, pero no esta Actiu</h1>
    <p>Posis en contacte amb el Administrador</p>
{% endblock %}

templates/reserves/no_usuari.html
{% extends 'base.html' %}
{% block contingut %}
    <h1> El usuari no Existeix</h1>
    <p>Posis en contacte amb el Administrador</p>
{% endblock %}

templates/reserves/nueva_reserva.html
{% extends 'base.html' %}
{% block titol %}<h1  class="titol">Nova Reserva {{ request.user.username }}</h1>{% endblock %}
{% block contingut %}

<!--<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css"> !-->
<link href="{{ STATIC_URL}}jquery.datetimepicker.css" rel="stylesheet" type="text/css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="{{ STATIC_URL}}jquery.datetimepicker.js"></script>
<script>
    $(document).ready(function(){

        $('#id_user option:eq({{usuario.id}})').prop('selected', true);
        //$('#id_user').prop('disabled',true);

        $('#id_data_inici').datetimepicker({
             format:'d/m/Y H:i',
        });
        $('#id_data_final').datetimepicker({
            format:'d/m/Y H:i',

        });



    })
</script>
    <h2 class="titol">Nova Reserva:</h2>

    <form id="formulario" method="POST" action="" >{% csrf_token %}
        <table>

    {% if formulario.errors %}
        {% for field in formulario %}
            {% for error in field.errors %}
                <div class="alert alert-error">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in formmulario.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    {%if error != 0 %}
            <p class="alerta">Exiteix una reserva del mateix element amb sol·lapació de dates </p>
    {% endif %}


        {% for field in formulario %}
            <tr><td>
            {{ field.name }}
            </td><td>
            {{ field }}
            </td></tr>
        {% endfor %}


         </table>
        <input type="submit" value="Reservar">
    </form>
{% endblock %}

templates/reserves/signup.html
{% extends 'base.html' %}
{% block contingut %}
    <form id='formulario' method="POST"  action=".">{% csrf_token %}
        <table>{{ formulario }}</table>
        <p><input type="submit" value="Regitrar"></p>
    </form>
{% endblock %}